[platformio]
default_envs = m5tools_core2_tough

[env]
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<*>

[env:m5tools_core2_tough]
platform = espressif32@4.4.0
board = m5stack-core2

lib_deps =
  m5stack/M5Unified@0.2.17
  m5stack/M5GFX@0.2.24

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -std=gnu++17

build_unflags =
  -std=gnu++11

[env:m5tools_tough_c5]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c5-devkitc-1
board_build.partitions = partitions_tough_c5.csv

lib_deps =
  https://github.com/m5stack/M5Unified.git#develop
  https://github.com/m5stack/M5GFX.git#develop

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -std=gnu++17
  -DARDUINO_M5STACK_TOUGHC5

build_unflags =
  -std=gnu++11
